@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}
###
GET {{BASE_URL}}/users


###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim" : "cetin1",
    "userName" : "cetin1",
    "email" : "buraka@gmasil.com",
    "sifre" : "12234"
}

###
PATCH  {{BASE_URL}}/users/60bbeadf5164033268d2a98d
Content-Type: application/json

{
    "isim" : "cetin-ceviz"
}

###
DELETE {{BASE_URL}}/users/60b76cb4f73d670990914b00
Content-Type: application/json