@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}
###
GET {{BASE_URL}}/users


###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim" : "Burakas",
    "userName" : "22adsasd",
    "email" : "burak2s04asd@gsmaiwl.com",
    "sifre" : "12345"
}

###
PATCH  {{BASE_URL}}/users/60b7480fefccb318b045455e
Content-Type: application/json

{

    "sifre" : "121231231",
    "isim" : "nakosanas"
}

###
DELETE {{BASE_URL}}/users/60b7449b6f0a972f4ceb164f
Content-Type: application/json